# Step 1: Import Data

In [12]:
import pandas as pd
import re

In [13]:
file_path = r'C:\Users\cau.tran\OneDrive\2. Study\13. Data Engineering with Unigap\Action 1\data.csv'

In [14]:
# file_path = r'C:\Users\Windows\OneDrive\2. Study\13. Data Engineering with Unigap\Action 1\data.csv'

In [15]:
raw = pd.read_csv(file_path)

In [16]:
raw.head()  # Display the first few rows of the DataFrame

,created_date,job_title,company,salary,address,time,link_description
0,2023-08-01,Business Analyst,Công ty TNHH Công nghệ số Adamo,10 - 20 triệu,Hà Nội,Còn 25 ngày để ứng tuyển,https://www.topcv.vn/viec-lam/business-analyst...
1,2023-08-01,Nhân Viên Lập Trình Phần Mềm - Thu Nhập Từ 10 ...,Công ty TNHH Đầu Tư Công Nghệ ST,10 - 20 triệu,Hồ Chí Minh,Còn 91 ngày để ứng tuyển,https://www.topcv.vn/viec-lam/nhan-vien-lap-tr...
2,2023-08-01,.Net Developer (N3) | T9160,Công ty TNHH CMC GLOBAL,Thoả thuận,Toàn Quốc,Còn 30 ngày để ứng tuyển,https://www.topcv.vn/viec-lam/net-developer-n3...
3,2023-08-01,"Project Manager (Tiếng Anh Giao Tiếp, Từ 1 Năm...",CÔNG TY CỔ PHẦN CÔNG NGHỆ SOTATEK,Tới 35 triệu,Hà Nội: Cầu Giấy,Còn 25 ngày để ứng tuyển,https://www.topcv.vn/viec-lam/project-manager-...
4,2023-08-01,Devops/Sre - Chuyên Viên Quản Trị Hệ Thống/Aut...,Công ty Cổ phần Thời Trang Yody,Tới 50 triệu,Hà Nội: Thanh Xuân: Hải Dương: TP Hải Dương,Còn 30 ngày để ứng tuyển,https://www.topcv.vn/viec-lam/devops-sre-chuye...

In [17]:
raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1933 entries, 0 to 1932
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   created_date      1933 non-null   object
 1   job_title         1933 non-null   object
 2   company           1933 non-null   object
 3   salary            1933 non-null   object
 4   address           1933 non-null   object
 5   time              1933 non-null   object
 6   link_description  1933 non-null   object
dtypes: object(7)
memory usage: 105.8+ KB

# Step 2: Data cleaning

## Yêu cầu 1: Chuẩn hóa và làm sạch dữ liệu

- Chuẩn hóa cột salary về dạng số, xử lý các giá trị như "Thoả thuận", "Trên X triệu", "X - Y triệu", "Tới X triệu", etc.
- Tạo thêm các cột phụ: min_salary, max_salary, salary_unit (VND/USD)
- Xử lý cột address để tách thành city và district
- Chuẩn hóa job_title để gom nhóm các vị trí tương tự (ví dụ: "Software Engineer", "Developer", "Programmer" có thể gom vào một nhóm)

Question

- Lương thỏa thuận thống nhất rule tách ra như thế nào? (để null hay giá trị 0) 
- Cột salary chứa text thì không format được sang dạng số >> Đề xuất khi tách ra 2 cột min & max sẽ format về dạng số
- Best practises để đặt tên các biến khi code?
- Tại sao lại có nhiều tỉnh, quận cho 1 dòng?
- Các để chuẩn hóa job_title nhanh

In [18]:
raw['salary'].unique()  # Check unique values in the salary column

array(['10 - 20 triệu', 'Thoả thuận', 'Tới 35 triệu', 'Tới 50 triệu',
       '12 - 18 triệu', '2 - 6 triệu', '3 - 6 triệu', 'Trên 1,000 USD',
       '10 - 30 triệu', '9 - 10 triệu', '30 - 35 triệu', '8 - 12 triệu',
       '9 - 12 triệu', '10 - 18 triệu', '600 - 1,300 USD', '3 - 8 triệu',
       'Trên 3 triệu', 'Tới 2,000 USD', 'Tới 40 triệu', '20 - 30 triệu',
       'Trên 12 triệu', 'Tới 30 triệu', '18 - 25 triệu', '7 - 8 triệu',
       'Tới 1,000 USD', '7 - 10 triệu', '20 - 40 triệu', '8 - 15 triệu',
       'Tới 750 USD', 'Tới 28 triệu', '12 - 20 triệu', '13 - 18 triệu',
       '1,000 - 2,000 USD', '13 - 20 triệu', 'Tới 1,500 USD',
       'Trên 20 triệu', '25 - 40 triệu', 'Tới 3 triệu', 'Tới 2 triệu',
       'Tới 20 triệu', 'Tới 3,000 USD', 'Tới 1,300 USD', '17 - 22 triệu',
       'Tới 15 triệu', '7 - 15 triệu', '3 - 5 triệu', '700 - 1,500 USD',
       'Tới 25 triệu', '10 - 15 triệu', 'Trên 10 triệu', 'Trên 1,700 USD',
       '20 - 35 triệu', '13 - 22 triệu', '10 - 12 triệu', 'Tới 1,800 USD',
       'Tới 2,500 USD', '9 - 15 triệu', '8 - 10 triệu', '30 - 60 triệu',
       '9 - 11 triệu', '15 - 25 triệu', '15 - 20 triệu', '8 - 20 triệu',
       '800 - 2,000 USD', '700 - 1,100 USD', '1,000 - 3,000 USD',
       '30 - 50 triệu', 'Tới 18 triệu', 'Tới 1,200 USD', 'Trên 8 triệu',
       'Trên 16 triệu', '1,200 - 1,800 USD', '15 - 22 triệu',
       'Tới 3.5 triệu', '17 - 27 triệu', 'Tới 4 triệu', '600 - 1,200 USD',
       '2,500 - 3,000 USD', '7 - 12 triệu', '20 - 45 triệu',
       '700 - 1,000 USD', '35 - 60 triệu', '18 - 22 triệu',
       '2 - 10 triệu', '10 - 25 triệu', 'Tới 45 triệu', '15 - 30 triệu',
       'Tới 12 triệu', '10 - 16 triệu', '10 - 14 triệu', '12 - 25 triệu',
       '11 - 16 triệu', '0.0 - 0.0 triệu', 'Tới 22 triệu',
       '25 - 30 triệu', '15 - 35 triệu', '6 - 10 triệu',
       'Trên 84,000 USD', '11 - 40 triệu', '18 - 28 triệu',
       'Trên 15 triệu', 'Tới 10 triệu', '6 - 8 triệu', '12 - 15 triệu',
       'Tới 13 triệu', 'Tới 9 triệu', '10 - 35 triệu', '500 - 1,200 USD',
       '10 - 27 triệu', '25 - 45 triệu', '15 - 40 triệu', 'Tới 8 triệu',
       '5 - 25 triệu', '25 - 32 triệu', '18 - 35 triệu', '600 - 800 USD',
       '7 - 9 triệu', '30 - 40 triệu', '20 - 60 triệu', 'Tới 2,300 USD',
       'Tới 14 triệu', '12 - 28 triệu', '12 - 38 triệu', '3 - 15 triệu',
       'Tới 16 triệu', 'Tới 26 triệu', '9 - 13 triệu', '900 - 1,200 USD',
       'Trên 13 triệu', '800 - 2,500 USD', 'Tới 5 triệu', 'Tới 55 triệu',
       '5 - 10 triệu', '35 - 45 triệu', 'Trên 363 USD', 'Tới 2,200 USD',
       'Trên 1,300 USD', '6 - 15 triệu', 'Trên 11 triệu',
       'Trên 1,500 USD', '2,000 - 4,000 USD', '13 - 15 triệu',
       '25 - 35 triệu', 'Tới 17 triệu', '1,200 - 2,000 USD',
       '20 - 25 triệu', 'Tới 11 triệu', '600 - 1,500 USD', 'Tới 6 triệu',
       '12 - 14 triệu', '1,000 - 1,400 USD', 'Tới 1,700 USD',
       '1,500 - 2,000 USD', 'Tới 1.3 triệu', 'Trên 14 triệu',
       '10 - 11 triệu', '20 - 33 triệu', 'Tới 4.6 triệu', '13 - 17 triệu',
       '1,300 - 1,700 USD', 'Trên 7 triệu', '18 - 30 triệu',
       'Tới 1,400 USD', '20 - 28 triệu', '10 - 13 triệu', '30 - 45 triệu',
       'Trên 18 triệu', '18 - 27 triệu', '8 - 35 triệu', '13 - 16 triệu',
       '1,200 - 2,500 USD', '1,400 - 2,000 USD', '9 - 20 triệu',
       '14 - 16 triệu', 'Tới 65 triệu', 'Tới 24 triệu', 'Trên 9 triệu',
       '15 - 18 triệu', '2 - 3 triệu', '55 - 70 triệu', '25 - 50 triệu',
       '4 - 8 triệu', '900 - 1,000 USD', 'Trên 1 triệu',
       '800 - 1,400 USD', '2 - 4 triệu', '1.2 - 2 triệu',
       '400 - 1,500 USD', '1,000 - 1,500 USD', '8 - 25 triệu',
       '7.5 - 14 triệu', 'Trên 700 USD', '5 - 15 triệu', '15 - 23 triệu',
       '5 - 5.5 triệu', '12 - 50 triệu', '3 - 4 triệu', 'Tới 23 triệu',
       '5 - 6 triệu', 'Trên 17 triệu', '12 - 17 triệu', 'Trên 2,000 USD',
       '13 - 30 triệu', 'Tới 30,000,000 USD', 'Trên 2.5 triệu',
       '700 - 2,000 USD', '700 - 1,200 USD',
       '10,000,000 - 14,000,000 USD', '1,000 - 2,500 USD', 'Trên 400 USD',
       '40 - 70 triệu', 'Trên 25 triệu', '2 - 8 triệu', '35 - 55 triệu',
       'Trên 30 triệu', '10 - 40 triệu', '23 - 28 triệu', '25 - 34 triệu',
       '15 - 50 triệu', '12 - 23 triệu', '1 - 3 triệu', 'Tới 80 triệu',
       '800 - 1,500 USD', 'Tới 7 triệu', 'Tới 42 triệu', 'Tới 48 triệu',
       'Tới 27.5 triệu', '25 - 37 triệu', '2,000 - 2,500 USD',
       'Tới 32 triệu', '400 - 450 USD', '700 - 900 USD', '14 - 17 triệu',
       '8 - 45 triệu', '2,000 - 3,000 USD', '450 - 900 USD',
       '2,200 - 2,700 USD', '20 - 32 triệu', '35 - 40 triệu',
       '25 - 55 triệu', '3 - 10 triệu', 'Trên 5 triệu', 'Tới 34 triệu',
       '20 - 55 triệu', 'Trên 600 USD', '750 - 1,000 USD',
       '600 - 750 USD', 'Trên 4 triệu', '4 - 5 triệu', '10 - 45 triệu',
       '18 - 23 triệu', '8 - 9 triệu', 'Tới 4.2 triệu', 'Trên 2 triệu',
       '10 - 17 triệu', '2.5 - 12 triệu', '500 - 800 USD',
       'Trên 0.0 triệu', '3.5 - 5 triệu', '35 - 50 triệu',
       'Trên 4.6 triệu', 'Trên 24 triệu', 'Tới 60 triệu',
       '1,000 - 1,800 USD', '8 - 13 triệu', '40 - 80 triệu',
       '8 - 18 triệu', '17 - 25 triệu', '16 - 22 triệu',
       '500 - 1,700 USD', 'Trên 6.5 triệu', 'Tới 800 USD', '6 - 30 triệu',
       '5 - 7 triệu', '6 - 9 triệu', 'Trên 900 USD', '14 - 40 triệu',
       'Tới 70 triệu', '10.3 - 20 triệu', 'Tới 27 triệu', 'Tới 38 triệu',
       'Trên 50 triệu', '15 - 17 triệu'], dtype=object)

In [19]:
df1 = raw.copy()

In [20]:
# Hàm xử lý salary
def extract_salary_range(s):
    s = s.lower().replace(',', '').strip()

    if 'usd' in s:
        currency = 'USD'
    elif 'triệu' in s:
        currency = 'VND'
    else:
        currency = 'Other'
    
    if 'thoả thuận' in s or 'thỏa thuận' in s:
        return None, None, currency

    if 'trên' in s:
        num = re.findall(r"[\d.]+", s)
        if num:
            val = float(num[0])
            return round(val, 2), None, currency

    if 'tới' in s or 'to' in s:
        num = re.findall(r"[\d.]+", s)
        if num:
            val = float(num[0])
            return None, round(val, 2), currency

    match = re.findall(r"[\d.]+", s)
    if len(match) == 2:
        return round(float(match[0]), 2), round(float(match[1]), 2), currency

    return None, None, currency

# Áp dụng tách lương
df1[['min_salary', 'max_salary','unit_currency']] = df1['salary'].apply(lambda x: pd.Series(extract_salary_range(x)))

# Kết quả
df1[['salary','min_salary','max_salary','unit_currency']]

             salary  min_salary  max_salary unit_currency
0     10 - 20 triệu        10.0        20.0           VND
1     10 - 20 triệu        10.0        20.0           VND
2        Thoả thuận         NaN         NaN         Other
3      Tới 35 triệu         NaN        35.0           VND
4      Tới 50 triệu         NaN        50.0           VND
...             ...         ...         ...           ...
1928     Thoả thuận         NaN         NaN         Other
1929   Trên 3 triệu         3.0         NaN           VND
1930   Tới 50 triệu         NaN        50.0           VND
1931     Thoả thuận         NaN         NaN         Other
1932     Thoả thuận         NaN         NaN         Other

[1933 rows x 4 columns]

In [21]:
df1.info()  # Check the DataFrame info to see the new columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1933 entries, 0 to 1932
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   created_date      1933 non-null   object
 1   job_title         1933 non-null   object
 2   company           1933 non-null   object
 3   salary            1933 non-null   object
 4   address           1933 non-null   object
 5   time              1933 non-null   object
 6   link_description  1933 non-null   object
 7   min_salary        709 non-null    float64
 8   max_salary        1098 non-null   float64
 9   unit_currency     1933 non-null   object
dtypes: float64(2), object(8)
memory usage: 151.1+ KB

In [22]:
def split_address_pairs(address):
    parts = [part.strip() for part in address.split(':')]
    result = {}
    for i in range(0, len(parts), 2):
        if i + 1 < len(parts):
            city_col = f'city_{i//2 + 1}'
            dist_col = f'district_{i//2 + 1}'
            result[city_col] = parts[i]
            result[dist_col] = parts[i + 1]
        else:
            # Nếu lẻ thì phần cuối cùng không có cặp -> gán riêng nếu muốn
            result[f'city_{i//2 + 1}'] = parts[i]
    return pd.Series(result)

# Áp dụng
df_split = df1['address'].apply(split_address_pairs)

# Gộp kết quả lại
df2 = df1.join(df_split)

df2.head()  # Hiển thị kết quả

,created_date,job_title,company,salary,address,time,link_description,min_salary,max_salary,unit_currency,city_1,district_1,city_2,district_2,city_3,district_3,city_4,district_4
0,2023-08-01,Business Analyst,Công ty TNHH Công nghệ số Adamo,10 - 20 triệu,Hà Nội,Còn 25 ngày để ứng tuyển,https://www.topcv.vn/viec-lam/business-analyst...,10.0,20.0,VND,Hà Nội,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-08-01,Nhân Viên Lập Trình Phần Mềm - Thu Nhập Từ 10 ...,Công ty TNHH Đầu Tư Công Nghệ ST,10 - 20 triệu,Hồ Chí Minh,Còn 91 ngày để ứng tuyển,https://www.topcv.vn/viec-lam/nhan-vien-lap-tr...,10.0,20.0,VND,Hồ Chí Minh,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-08-01,.Net Developer (N3) | T9160,Công ty TNHH CMC GLOBAL,Thoả thuận,Toàn Quốc,Còn 30 ngày để ứng tuyển,https://www.topcv.vn/viec-lam/net-developer-n3...,NaN,NaN,Other,Toàn Quốc,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-08-01,"Project Manager (Tiếng Anh Giao Tiếp, Từ 1 Năm...",CÔNG TY CỔ PHẦN CÔNG NGHỆ SOTATEK,Tới 35 triệu,Hà Nội: Cầu Giấy,Còn 25 ngày để ứng tuyển,https://www.topcv.vn/viec-lam/project-manager-...,NaN,35.0,VND,Hà Nội,Cầu Giấy,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-08-01,Devops/Sre - Chuyên Viên Quản Trị Hệ Thống/Aut...,Công ty Cổ phần Thời Trang Yody,Tới 50 triệu,Hà Nội: Thanh Xuân: Hải Dương: TP Hải Dương,Còn 30 ngày để ứng tuyển,https://www.topcv.vn/viec-lam/devops-sre-chuye...,NaN,50.0,VND,Hà Nội,Thanh Xuân,Hải Dương,TP Hải Dương,NaN,NaN,NaN,NaN

In [23]:
# Kiểm tra lại data tỉnh, quận
# df2.to_csv(r'C:\Users\Windows\OneDrive\2. Study\13. Data Engineering with Unigap\Action 1\data_processed.csv', index=False, encoding='utf-8-sig')

In [24]:
# Kiểm tra các giá trị duy nhất trong cột 'job_title'
# df2['job_title'].to_csv(r'C:\Users\Windows\OneDrive\2. Study\13. Data Engineering with Unigap\Action 1\job_title.csv', index=False, encoding='utf-8-sig')  # Lưu job_title vào file CSV

In [25]:
group_keywords = {
    'Software Engineer': ['developer', 'software engineer', 'programmer', 'coder', 'lập trình'],
    'Data': ['data', 'analyst', 'bi', 'business analyst'],
    'DevOps': ['devops', 'sre', 'system admin'],
    'PM': ['project manager', 'scrum master', 'product owner'],
    'IT Support': ['it support', 'helpdesk', 'technical support', 'application support'],
    'Tester': ['qa', 'qc', 'tester', 'kiểm thử'],
    'Intern': ['thực tập', 'intern'],
    'Other': []  # fallback nếu không khớp gì
}

nlp - natural language processing

fuzzy - khớp bao nhiêu % (tách từng ký tự)

In [26]:
def normalize_job_title(title):
    title = str(title).lower()
    for group, keywords in group_keywords.items():
        if any(keyword in title for keyword in keywords):
            return group
    return 'Other'

In [27]:
df2['job_group'] = df2['job_title'].apply(normalize_job_title)

In [28]:
df2.head()  # Hiển thị kết quả

,created_date,job_title,company,salary,address,time,link_description,min_salary,max_salary,unit_currency,city_1,district_1,city_2,district_2,city_3,district_3,city_4,district_4,job_group
0,2023-08-01,Business Analyst,Công ty TNHH Công nghệ số Adamo,10 - 20 triệu,Hà Nội,Còn 25 ngày để ứng tuyển,https://www.topcv.vn/viec-lam/business-analyst...,10.0,20.0,VND,Hà Nội,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Data
1,2023-08-01,Nhân Viên Lập Trình Phần Mềm - Thu Nhập Từ 10 ...,Công ty TNHH Đầu Tư Công Nghệ ST,10 - 20 triệu,Hồ Chí Minh,Còn 91 ngày để ứng tuyển,https://www.topcv.vn/viec-lam/nhan-vien-lap-tr...,10.0,20.0,VND,Hồ Chí Minh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Engineer
2,2023-08-01,.Net Developer (N3) | T9160,Công ty TNHH CMC GLOBAL,Thoả thuận,Toàn Quốc,Còn 30 ngày để ứng tuyển,https://www.topcv.vn/viec-lam/net-developer-n3...,NaN,NaN,Other,Toàn Quốc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Software Engineer
3,2023-08-01,"Project Manager (Tiếng Anh Giao Tiếp, Từ 1 Năm...",CÔNG TY CỔ PHẦN CÔNG NGHỆ SOTATEK,Tới 35 triệu,Hà Nội: Cầu Giấy,Còn 25 ngày để ứng tuyển,https://www.topcv.vn/viec-lam/project-manager-...,NaN,35.0,VND,Hà Nội,Cầu Giấy,NaN,NaN,NaN,NaN,NaN,NaN,PM
4,2023-08-01,Devops/Sre - Chuyên Viên Quản Trị Hệ Thống/Aut...,Công ty Cổ phần Thời Trang Yody,Tới 50 triệu,Hà Nội: Thanh Xuân: Hải Dương: TP Hải Dương,Còn 30 ngày để ứng tuyển,https://www.topcv.vn/viec-lam/devops-sre-chuye...,NaN,50.0,VND,Hà Nội,Thanh Xuân,Hải Dương,TP Hải Dương,NaN,NaN,NaN,NaN,DevOps